# Generated by Django 5.1.2 on 2025-02-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_modelovestigio'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Público'), (2, 'Privado')], default=1),
        ),
        migrations.AddField(
            model_name='modelovestigio',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Público'), (2, 'Privado')], default=1),
        ),
    ]
