# Generated by Django 5.1.2 on 2025-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_modelo_type_modelovestigio_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variavel', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Armamento'), (2, 'Arquivo Digital'), (3, 'Dispositivo Tecnológico'), (4, 'Documento'), (5, 'Impressão Papiloscópica'), (6, 'Material'), (7, 'Objeto'), (8, 'Veículo')])),
            ],
            options={
                'verbose_name': 'Variável',
                'verbose_name_plural': 'Variáveis',
                'db_table': 'variaveis',
            },
        ),
    ]
