# Generated by Django 5.1.2 on 2025-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_variavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelovestigio',
            name='type_vestigio',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Público'), (2, 'Privado')], default=1),
        ),
    ]
