# Generated by Django 5.1.6 on 2025-02-17 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_modelovestigio_type_vestigio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelovestigio',
            name='type_vestigio',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Armamento'), (2, 'Arquivo Digital'), (3, 'Dispositivo Tecnológico'), (4, 'Documento'), (5, 'Impressão Papiloscópica'), (6, 'Material'), (7, 'Objeto'), (8, 'Veículo')], default=1),
        ),
        migrations.AlterField(
            model_name='variavel',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Geral'), (1, 'Armamento'), (2, 'Arquivo Digital'), (3, 'Dispositivo Tecnológico'), (4, 'Documento'), (5, 'Impressão Papiloscópica'), (6, 'Material'), (7, 'Objeto'), (8, 'Veículo')]),
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aberto'), (2, 'Em Andamento'), (3, 'Finalizado')], default=1)),
                ('responsavel', models.PositiveSmallIntegerField(choices=[(1, 'Cliente'), (2, 'Admin')], default=2)),
                ('urgencia', models.PositiveSmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2)),
                ('date_inclusion', models.DateTimeField(auto_now_add=True)),
                ('user_inclusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'db_table': 'chamados',
            },
        ),
        migrations.CreateModel(
            name='RespostaChamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('date_inclusion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='mysite.chamado')),
            ],
            options={
                'verbose_name': 'Resposta de Chamado',
                'verbose_name_plural': 'Respostas de Chamados',
                'db_table': 'respostas_chamados',
            },
        ),
    ]
