# Generated by Django 5.1.6 on 2025-02-18 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='cabecalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.media'),
        ),
    ]
